### ISSUE TITLE
exclude hashtags

### ISSUE THREAD

**Issue by robsonsobral** [erpheus/hideit-bot#2]
Hi!

Really useful bot! Congratulations!

Is it possible to exclude hashtags, so we can send something like `@hideitBot #spoiler CharacterX dies tonight episode` or `#nsfw @hideitBot something non Catholic`

Thank you!

**Comment by erpheus** [comment]
Hello!
Sorry for my late reply. You can actually achieve what you want by enclosing the part of the message you want to hide in asterisks:

`@hideitBot #spoiler *CharacterX dies tonight episode*`

![img_2352](https://cloud.githubusercontent.com/assets/331330/20431520/acc5581e-ad9a-11e6-8f8c-627d749e644e.PNG)

**Comment by robsonsobral** [comment]
No problem!

Asterisks? Really? This is new! I hope this don't cause issues. Who knows if Telegram enables markdown some day?

Thank you! For your attention and for the bot! Thank you!
