### ISSUE TITLE
@hideitBot cannot be added to groups

### ISSUE THREAD

**Issue by rantonels** [erpheus/hideit-bot#3]
Not really a problem with the code itself, but I wouldn't know where to ask.

Since a few days @hideitBot has left groups and cannot be added back. It seems as though the option for being able to be added to groups is disabled on BotFather.

The bot seems to work flawlessly in private conversations.

**Comment by erpheus** [comment]
You're right. I never explicitly allowed it as the bot is meant to be used inline. Maybe with a recent update the default settings were changed.

Still I'm not sure it should be allowed. As far as I can see you don't need it in a group for anything. Could you tell me your use case?

**Comment by rantonels** [comment]
Ok, I learned something new about telegram bots today. Inline bots can work without being members of the conversation.

Thanks!
