### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by dekiesel** [erpheus/hideit-bot#5]
Hi,

The bot isn't responding. Do you have any plans to update it?

Thank you for your work!

**Comment by erpheus** [comment]
Hello!

Yes, I noticed that approximately since the 25th of May it hasn’t been responding. The bot program is alive and running but has lots of telegram errors on the logs, I guess some change in Telegram’s bot API messed something up. I’ll try to take a look at it next week.

Cheers!

**Comment by dekiesel** [comment]
@erpheus thank you very much!

**Comment by erpheus** [comment]
Hello!

I managed to get it working again. Telegram has changed several things to its API since I deployed the bot and I had an outdate version of the library I use to connect to telegram.

My patch has been a bit dirty but it should keep working for a while now.
