### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by ghost** [erpheus/hideit-bot#9]
Hello!

Sorry for bother you but today HideitBot stop working. Has it dissappear? It's the only GOOD (like REALLY good) spoiler bot out tthere and it will be a HUGE LOSS if it stop working.

**Comment by erpheus** [comment]
Thanks for all the praise! 😄 I actually don't use it much but I try to check from time to time to see if it is still working. It seems like some DNS error caused it to go down a couple of days ago. But it is back online now 😊 

Thanks for the report!
